### ISSUE TITLE
TODO and unsupported assets

### ISSUE THREAD

**Issue by PiKeyAr** [PiKeyAr/sadx-hd-gui#1]
Possible improvements for current assets:
- [ ] Make the frame in J and E level objectives more consistent (@DisapprovingOwl and/or @SPEEPSHighway)
- [ ] Remake text in Japanese maps

**Unsupported assets (currently not scaled by the Mod Loader)**
- [ ] Subtitle font
- [ ] Mini Game Collection main menu 
- [ ] Mini Game Collection tutorial 
- [ ] Mini Game Collection pause 
- [ ] Chao fonts 
- [ ] Chao button prompts (removed in DC_ChaoGardens)
- [ ] Name Machine UI 
- [ ] Black Market UI 
- [ ] Chao Race Entry UI 
- [ ] Chao Race HUD

**Comment by fancymelonub** [comment]
This looks cool! I think I know you for making/helping on big mods for SADX.

**Comment by rms1229** [comment]
I look forward to the Game Gear stuff. Also, I'm curious, how do you go about making this stuff anyway?

**Comment by Shadowboxer2005** [comment]
Suggestion: DX Title screen graphics. (The game **does** include HD Title graphics, but it's not smooth)
![sonicadventuredxpc 10_02_2019 12_03_31 pm](https://user-images.githubusercontent.com/43715619/52528185-fc39c980-2d2b-11e9-8416-fe2a616a4dd1.png)
Notices how the shading is sharp.

**Comment by RinMaru** [comment]
> Suggestion: DX Title screen graphics. (The game does include HD Title graphics, but it's not smooth)
> 
> Notice how the shading is sharp.

just run it through Topaz Gigapixel AI

**Comment by PiKeyAr** [comment]
The title screen is currently not adjusted by the Mod Loader and still stretched out at 16:9, so I prefer to avoid touching it until it's supported.

**Comment by Shadowboxer2005** [comment]
Ok.

**Comment by SirYodaJedi** [comment]
[This is my attempt at smoothing out the Title Screen text.](https://cdn.discordapp.com/attachments/446023672147345420/667026842355630110/AVA_GTITLE0_E.pvmx) Sonic would be a lot more difficult, of course.

**Comment by PiKeyAr** [comment]
Thanks for the contribution. I'd like to tackle that once the DX title screen is properly scaled/stretched in the Mod Loader (see https://github.com/sonicretro/sadx-mod-loader/issues/8#issuecomment-575872704).

**Comment by PiKeyAr** [comment]
Btw I just checked the file... and it has the same resolution textures as the original?
For HD GUI 2 we need at least 2x, ideally 3x size textures.

**Comment by SirYodaJedi** [comment]
> Btw I just checked the file... and it has the same resolution textures as the original?
> For HD GUI 2 we need at least 2x, ideally 3x size textures.

I didn't upscale them, just remove the banding. This is the version I use in my SADX installation; I posted it here as a cleaner starting point, moreso than a final product.

The logo was taken from [SteamGridDB](https://www.steamgriddb.com/logo/110), and Press Enter only actually has the main color gradient changed.
![6789CD38-C6A7-4A68-9C7D-C77963E94B41](https://user-images.githubusercontent.com/50331474/72666144-541d8d80-39dd-11ea-9898-efa365061d1e.png)

**Comment by PiKeyAr** [comment]
I was able to find a Sonic render without color banding in SADX autorun.exe, unfortunately it's pretty small and the bottom is obscured by the game's logo.
![image](https://user-images.githubusercontent.com/23312549/73611588-9cb48800-4626-11ea-93f7-612c3786943e.png)
There's also this image that was first used in Humble Bundle (apparently) but it's too JPEG-y
![image](https://user-images.githubusercontent.com/23312549/73611642-32e8ae00-4627-11ea-920e-7ff1389500a2.png)

**Comment by PiKeyAr** [comment]
Here's our best bet though: https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Various/sonic.png
Need to cut it from the background and fake the DX plastic lighting somehow
